version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run:
          name: Install coverage
          command: pip install coverage
      - run:
          name: Run tests with coverage
          command: coverage run setup.py test
      - run:
          name: Send coverage results to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  test_and_upload_coverage:
    jobs:
      - test
